//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVD.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arenda
    {
        public Arenda()
        {
            this.Check = new HashSet<Check>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> D_vidachi { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_sotrudnika { get; set; }
        public Nullable<System.DateTime> D_sdachi { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
        public virtual ICollection<Check> Check { get; set; }
    }
}
