//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVD.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.Check = new HashSet<Check>();
            this.Film_Zhanr = new HashSet<Film_Zhanr>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> id_vozr_ogranich { get; set; }
        public Nullable<double> cost_arend { get; set; }
    
        public virtual ICollection<Check> Check { get; set; }
        public virtual Vozrast Vozrast { get; set; }
        public virtual ICollection<Film_Zhanr> Film_Zhanr { get; set; }
    }
}
