//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVD.Connection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DVDEntities1 : DbContext
    {
        public DVDEntities1()
            : base("name=DVDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Arenda> Arenda { get; set; }
        public DbSet<Check> Check { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Film> Film { get; set; }
        public DbSet<Film_Zhanr> Film_Zhanr { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Sotrudnik> Sotrudnik { get; set; }
        public DbSet<Vozrast> Vozrast { get; set; }
        public DbSet<Zhanr> Zhanr { get; set; }
    }
}
