//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVD.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Sotrudnik = new HashSet<Sotrudnik>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Sotrudnik> Sotrudnik { get; set; }
    }
}
