//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVD.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public Sotrudnik()
        {
            this.Arenda = new HashSet<Arenda>();
        }
    
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Id_role { get; set; }
        public Nullable<double> Salary { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Arenda> Arenda { get; set; }
        public virtual Role Role { get; set; }
    }
}
